name: Update CSV

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *' # Executar a cada 30 minutos

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script to update CSV
      run: python update_csv.py

    - name: Commit and push changes
      run: |
        git add tide_data.csv
        git commit -m "Update CSV"
        git push
