name: Update and deploy

on:
  push:
    branches:
      - main

jobs:
  update_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Google Chrome
        run: |
          wget -q -O /tmp/google-chrome-stable_current_amd64.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i /tmp/google-chrome-stable_current_amd64.deb || true
          sudo apt-get install -y -f

      - name: Install ChromeDriver
        run: |
          VERSION=$(wget -q -O - https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget -q -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/$VERSION/chromedriver_linux64.zip"
          unzip /tmp/chromedriver.zip -d /tmp
          sudo mv /tmp/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Set up ChromeDriver environment
        run: echo "export PATH=$PATH:/usr/local/bin" >> $GITHUB_ENV

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python main.py

      - name: Move graph to output directory
        run: mv grafico.png output/

      - name: Commit and push changes
        run: |
          git config --global user.email "luizdavilaf@gmail.com"
          git config --global user.name "Luiz Davila"
          git add output/grafico.png
          git commit -m "Update graph"
          git push
